#!/bin/bash

# CODE IN HEADER FILE
HEADER_N=$(echo $1 | tr 'a-z' 'A-Z' | tr '.' '_')
HEADER_F="#ifndef $HEADER_N\n#define MAIN_H\n\n#endif"

# CODE IN MAIN FILE
MAIN_FILE="#include \"main.h\"\n\n/\*\*\n* main - Entry point\n\*\n\* Return: Always 0 (Success)\n\*/\nint main(void)\n{\n\treturn (0);\n}"

# CODE IN FUNC FILE
FUNC_FILE="#include \"main.h\"\n\n/\*\*\n\* func - Entry point...\n\* Description: 'the program desc'\n\* Return: Always 0 (Success)\n\* @a: int parmameter\n  \* @b: int parmameter\n*/\n\nint func (int a, int b)\n{\n\treturn (a + b);\n}"

# GET EXTENTION FILE
FILE_N=$(echo $1 | rev | cut -d '.' -f1)

# CHECK EXTENTION FILE
if [ -z "$FILE_N" ]
then
	echo -e "mcode [FILE NAME]\n"
	exit 1
elif [ "$FILE_N" = "h" ]
then
	echo -e  $HEADER_F > $1
elif [ "$FILE_N" = "c" ]
then
	echo -e "What type of c file ?\n1) Main.c\n2) Function.c\n"
	read -p "File :" ty
	[ $ty = "1" ] && echo -e $MAIN_FILE >> $1 || echo -e $FUNC_FILE >> $1
fi

# LAUNCH VIM
vim "$1" && chmod u+x $1;
